version: "3.8"

x-healthcheck-defaults: &healthcheck_defaults
  interval: 10s  # 间隔
  timeout: 5s  # 超时
  retries: 5  # 连续失败次数
  start_period: 10s # 初始化时间

services:

  webstack-go-service:
    container_name: webstack-go-service
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "9999:9999"
    volumes:
      - ./configs:/opt/configs
      - ./logs/:/opt/logs/
      - ./assets/upload/:/opt/assets/upload
    networks:
      - webstack-go
    healthcheck:
      test: "/bin/netstat -anpt|grep 9999"
      <<: *healthcheck_defaults
    depends_on:
      webstack-go-mysql:
        condition: service_healthy
      webstack-go-redis:
        condition: service_healthy


  webstack-go-mysql:
    image: mysql/mysql-server:5.7
    container_name: webstack-go-mysql
    environment:
      MYSQL_DATABASE: webstack-go
      TZ: Asia/Shanghai
      # 允许来自其他主机的根连接
      # https://dev.mysql.com/doc/refman/5.7/en/docker-mysql-more-topics.html#docker_var_mysql-root-host
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - webstack-go
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      <<: *healthcheck_defaults


  webstack-go-redis:
    image: redis:6.2.4
    container_name: webstack-go-redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    networks:
      - webstack-go
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      <<: *healthcheck_defaults


networks:
  webstack-go:
    driver: bridge
    name: webstack-go
