version: "3.8"

services:

  webstack-go-prometheus:
    image: prom/prometheus:latest
    container_name: webstack-go-prometheus
    volumes:
      - ./deployments/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - webstack-go

  webstack-go-grafana:
    image: grafana/grafana-enterprise:9.4.3
    container_name: webstack-go-grafana
    ports:
      - "3000:3000"
    networks:
      - webstack-go

  webstack-go-loki:
    image: grafana/loki:2.7.3
    container_name: webstack-go-loki
    user: root
    volumes:
      - ./deployments/loki/loki.yaml:/etc/loki/loki.yaml
    command: -config.file=/etc/loki/loki.yaml
    ports:
      - "3100:3100"
    networks:
      - webstack-go

  webstack-go-promtail:
    image: grafana/promtail:2.7.3
    container_name: webstack-go-promtail
    user: root
    volumes:
      - ./logs/:/data/logs/
      - ./deployments/loki/promtail.yaml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - webstack-go


networks:
  webstack-go:
    driver: bridge
    name: webstack-go