// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStSite = "st_site"

// StSite mapped from table <st_site>
type StSite struct {
	ID          int        `gorm:"column:id;type:INTEGER" json:"id"`
	CategoryID  int        `gorm:"column:category_id;type:int(11)" json:"category_id"`
	Title       string     `gorm:"column:title;type:varchar(50)" json:"title"`
	Icon        string     `gorm:"column:icon;type:varchar(255)" json:"icon"`
	Description string     `gorm:"column:description;type:varchar(500)" json:"description"`
	URL         string     `gorm:"column:url;type:varchar(255);not null" json:"url"`
	IsUsed      bool       `gorm:"column:is_used;type:bool;default:false" json:"is_used"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP not null" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP not null" json:"updated_at"`
	DeletedAt   *time.Time `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName StSite's table name
func (*StSite) TableName() string {
	return TableNameStSite
}
