// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysUserMenu = "sys_user_menu"

// SysUserMenu mapped from table <sys_user_menu>
type SysUserMenu struct {
	ID        int        `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	UserID    int        `gorm:"column:user_id;type:int(11);not null" json:"user_id"`
	MenuID    int        `gorm:"column:menu_id;type:int(11);not null" json:"menu_id"`
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP not null" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP not null" json:"updated_at"`
	DeletedAt *time.Time `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName SysUserMenu's table name
func (*SysUserMenu) TableName() string {
	return TableNameSysUserMenu
}
