// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysConfig = "sys_config"

// SysConfig mapped from table <sys_config>
type SysConfig struct {
	ID          int    `gorm:"column:id;type:INTEGER" json:"id"`
	AboutSite   string `gorm:"column:about_site;type:text" json:"about_site"`
	AboutAuthor string `gorm:"column:about_author;type:text" json:"about_author"`
	IsAbout     bool   `gorm:"column:is_about;type:bool;default:false" json:"is_about"`
	SiteTitle   string `gorm:"column:site_title;type:varchar(50)" json:"site_title"`
	SiteKeyword string `gorm:"column:site_keyword;type:text" json:"site_keyword"`
	SiteDesc    string `gorm:"column:site_desc;type:text" json:"site_desc"`
	SiteRecord  string `gorm:"column:site_record;type:varchar(500)" json:"site_record"`
}

// TableName SysConfig's table name
func (*SysConfig) TableName() string {
	return TableNameSysConfig
}
