// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysMenu = "sys_menu"

// SysMenu mapped from table <sys_menu>
type SysMenu struct {
	ID        int        `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	Pid       int        `gorm:"column:pid;type:int(11);not null" json:"pid"`
	Name      string     `gorm:"column:name;type:varchar(32);not null" json:"name"`
	Link      string     `gorm:"column:link;type:varchar(100);not null" json:"link"`
	Icon      string     `gorm:"column:icon;type:varchar(60);not null" json:"icon"`
	Level     int        `gorm:"column:level;type:int(11);default:1" json:"level"`
	Sort      int        `gorm:"column:sort;type:int(11);not null" json:"sort"`
	IsUsed    bool       `gorm:"column:is_used;type:bool;default:false" json:"is_used"`
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP not null" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP not null" json:"updated_at"`
	DeletedAt *time.Time `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}
