// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdmin = "admin"

// Admin mapped from table <admin>
type Admin struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`
	Username    string    `gorm:"column:username;not null;comment:用户名" json:"username"`
	Password    string    `gorm:"column:password;not null;comment:密码" json:"password"`
	Nickname    string    `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`
	Mobile      string    `gorm:"column:mobile;not null;comment:手机号" json:"mobile"`
	IsUsed      int64     `gorm:"column:is_used;not null;default:1;comment:是否启用 1:是  -1:否" json:"is_used"`
	IsDeleted   int64     `gorm:"column:is_deleted;not null;default:-1;comment:是否删除 1:是  -1:否" json:"is_deleted"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`
	CreatedUser string    `gorm:"column:created_user;not null;comment:创建人" json:"created_user"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`
	UpdatedUser string    `gorm:"column:updated_user;not null;comment:更新人" json:"updated_user"`
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}
