// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminMenu = "admin_menu"

// AdminMenu mapped from table <admin_menu>
type AdminMenu struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`
	AdminID     int64     `gorm:"column:admin_id;not null;comment:管理员ID" json:"admin_id"`
	MenuID      int64     `gorm:"column:menu_id;not null;comment:菜单栏ID" json:"menu_id"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`
	CreatedUser string    `gorm:"column:created_user;not null;comment:创建人" json:"created_user"`
}

// TableName AdminMenu's table name
func (*AdminMenu) TableName() string {
	return TableNameAdminMenu
}
