// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuthorized = "authorized"

// Authorized mapped from table <authorized>
type Authorized struct {
	ID                int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`
	BusinessKey       string    `gorm:"column:business_key;not null;comment:调用方key" json:"business_key"`
	BusinessSecret    string    `gorm:"column:business_secret;not null;comment:调用方secret" json:"business_secret"`
	BusinessDeveloper string    `gorm:"column:business_developer;not null;comment:调用方对接人" json:"business_developer"`
	Remark            string    `gorm:"column:remark;not null;comment:备注" json:"remark"`
	IsUsed            int64     `gorm:"column:is_used;not null;default:1;comment:是否启用 1:是  -1:否" json:"is_used"`
	IsDeleted         int64     `gorm:"column:is_deleted;not null;default:-1;comment:是否删除 1:是  -1:否" json:"is_deleted"`
	CreatedAt         time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`
	CreatedUser       string    `gorm:"column:created_user;not null;comment:创建人" json:"created_user"`
	UpdatedAt         time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`
	UpdatedUser       string    `gorm:"column:updated_user;not null;comment:更新人" json:"updated_user"`
}

// TableName Authorized's table name
func (*Authorized) TableName() string {
	return TableNameAuthorized
}
