// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMenuAction = "menu_action"

// MenuAction mapped from table <menu_action>
type MenuAction struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`
	MenuID      int64     `gorm:"column:menu_id;not null;comment:菜单栏ID" json:"menu_id"`
	Method      string    `gorm:"column:method;not null;comment:请求方式" json:"method"`
	API         string    `gorm:"column:api;not null;comment:请求地址" json:"api"`
	IsDeleted   int64     `gorm:"column:is_deleted;not null;default:-1;comment:是否删除 1:是  -1:否" json:"is_deleted"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`
	CreatedUser string    `gorm:"column:created_user;not null;comment:创建人" json:"created_user"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`
	UpdatedUser string    `gorm:"column:updated_user;not null;comment:更新人" json:"updated_user"`
}

// TableName MenuAction's table name
func (*MenuAction) TableName() string {
	return TableNameMenuAction
}
