// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMenu = "menu"

// Menu mapped from table <menu>
type Menu struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`
	Pid         int64     `gorm:"column:pid;not null;comment:父类ID" json:"pid"`
	Name        string    `gorm:"column:name;not null;comment:菜单名称" json:"name"`
	Link        string    `gorm:"column:link;not null;comment:链接地址" json:"link"`
	Icon        string    `gorm:"column:icon;not null;comment:图标" json:"icon"`
	Level       int64     `gorm:"column:level;not null;default:1;comment:菜单类型 1:一级菜单 2:二级菜单" json:"level"`
	Sort        int64     `gorm:"column:sort;not null;comment:排序" json:"sort"`
	IsUsed      int64     `gorm:"column:is_used;not null;default:1;comment:是否启用 1:是 -1:否" json:"is_used"`
	IsDeleted   int64     `gorm:"column:is_deleted;not null;default:-1;comment:是否删除 1:是  -1:否" json:"is_deleted"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`
	CreatedUser string    `gorm:"column:created_user;not null;comment:创建人" json:"created_user"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`
	UpdatedUser string    `gorm:"column:updated_user;not null;comment:更新人" json:"updated_user"`
}

// TableName Menu's table name
func (*Menu) TableName() string {
	return TableNameMenu
}
